### ISSUE TITLE
Forced boot into Gallery Mode

### ISSUE THREAD

**Issue by mxze** [kavezo/MagiReco_NA_Server#13]
As of a little while after NA magireco has shut down, the private server no longer works as the game seems to force itself into gallery mode shortly after starting up the game/before you get to the title screen. There's seemingly no workaround for this on our side; I thought maybe setting the time backwards on my device could trick the game as I had seen people set the time forwards before the shutdown to access gallery mode in advance, but setting the time backwards just gave me a connection error 1 and no bootup at all.

**Comment by Blinding-Awesomeness** [comment]
I have the same issue. Tried it on Version 1.2.0 from the Google Play Store with all the assets downloaded before the shutdown and debugSigned copies from mo.qyu.be (Version 1.1.13 and 1.2.0). On the debugSigned copies, I couldn't get most assets to load before the shutdown, but now it goes straight to Gallery Mode.

**Comment by kavezo** [comment]
Yep, this was an issue with the server; it turns out it did a DNS query on open that we failed to catch, and the people at magica-us.com apparently took it down immediately after closure. We're working on an update that will catch those DNS queries.

**Comment by Blinding-Awesomeness** [comment]
Thanks for the heads up. Good luck on the fix, and let me know if you need anything from me.

**Comment by kavezo** [comment]
It should be fixed in the latest release!
