### ISSUE TITLE
Should probably move `data` directory out of version control

### ISSUE THREAD

**Issue by dburr** [kavezo/MagiReco_NA_Server#23]
Right now upgrading through git is a pain, because it always complains that files under `data/` have been modified and prevents the git upgrade from continuing.

Here's a suggestion for how to deal with this:

- rename the current `data/` to something else, say, `data.template/`
- when setting up the server or running it for the first time, if `data/` does not exist, copy the contents of `data.template/` to `data/`
- put `data/` into `.gitignore` (since now the `data/` directory will contain files that are being modified by the active server)

hope this makes sense, it is really late and I am tired lol

**Comment by kavezo** [comment]
Sounds good! There *are* a few things in the data folder we want to keep though -- we need to update the full memoria list when we finally get MKR trio flower field, as well as any other missing information about battles and the like, and perhaps we want to change the default user in the future. But it'd be a good idea to remove data/user and on server start, copy over the default user data if data/user doesn't exist

**Comment by kavezo** [comment]
done
