### ISSUE TITLE
Black screen on bootup

### ISSUE THREAD

**Issue by mxze** [kavezo/MagiReco_NA_Server#24]
On the latest update, I'm able to do nearly everything fine. I was able to set up the server, install the certificate and profile, and I was able to boot up the server with seemingly no problems (telling me the app and dns servers have started). When I boot up magireco (after changing my DNS settings) it shows the usual logos and age disclaimer and then it very briefly shows the loading screen, then it goes black with nothing booting up at all (no gallery mode, no normal title screen). I can tap the screen but it does nothing. I saw others saying they had this problem on android but I'm on an ipad so I'm not sure if that correlates with the problem. I wish I could give more information but I think this is all I have, if there's anything else I can do to help describe the problem please let me know.
Thank you contributors for your hard work on this project!!

**Comment by gvaldebenit** [comment]
According to some messages, it is due to cert problems. Make sure you installed the cert correctly. If you don't have one, or runned setupServer.bat again, the cert changes, and you need to install the new generated cert (after deleting the old one obviously)

**Comment by mxze** [comment]
> According to some messages, it is due to cert problems. Make sure you installed the cert correctly. If you don't have one, or runned setupServer.bat again, the cert changes, and you need to install the new generated cert (after deleting the old one obviously)

It should be installed correctly, I've checked to make sure the profile I have on my ipad matches up with the cert it should have installed and all of the details check out. All of my older certs were deleted already. It's the certificate I got after downloading the new release and running setupServer.bat once, so I know it's the right one/I haven't made a new one I need to install.
Is there any other details I should check to make sure it's not something on my part that went wrong?

**Comment by gvaldebenit** [comment]
Not sure what could it be then. Someone suggested to visit, with DNS enabled, https://android.magica-us.com/ on web browser (of your device) to test if DNS and cert works fine.

**Comment by dburr** [comment]
@mxze just to clarify, you went to Settings -> General -> About -> Certificate Trust Settings and turned ON the switch next to the magica.us cert?

**Comment by kavezo** [comment]
We may have found the root cause...what Android version do you use? It looks like Android 9 and up only supports encrypted DNS on a system-wide level: https://www.androidpolice.com/2020/03/26/make-android-use-dns-server-choice/#Android_9_Pie_and_newer which...we do not have xd

I don't know the status of non-system-wide DNS settings. If you can still edit DNS for specific networks, would it still give you the black screen?

**Comment by mxze** [comment]
@dburr oml, i forgot to do that. I did it now and it works flawlessly, thank you so much!!!!! I think I had overlooked doing it after I had installed the profile..and sorry about all of this when it was an error on my part.

**Comment by dburr** [comment]
@mxze np, glad it's working for you now!
