### ISSUE TITLE
setupServer.bat does not make a certificate

### ISSUE THREAD

**Issue by popinloopy** [kavezo/MagiReco_NA_Server#29]
As the title says, running setupServer.bat like it says to in the instructions does not create a certificate file. If I append "pause" to the end of it to see the error, it says the following.
![image](https://user-images.githubusercontent.com/15270262/98447633-f1bc8780-20eb-11eb-9576-ab9f266ccf8a.png)

**Comment by SuzukaGozen** [comment]
Looks like you downloaded just the source code. For Windows you need to download the ZipZap archive from releases https://github.com/kavezo/ZipZap/releases

**Comment by popinloopy** [comment]
That would do it. Thank you!
