### ISSUE TITLE
Mirrors error: Missing file

### ISSUE THREAD

**Issue by Darkstar0001** [kavezo/MagiReco_NA_Server#38]
Mirrors was working in the v 0.4 update, but now gives an error [500]. The command line outputs FileNotFoundError: [Errno 2] No such file or directory: 'data/user/userArenaBattleResult.json'

On a possibly unrelated note, I got this message on boot: "InsecureRequestWarning: Unverified HTTPS request is being made to host 'endless.snaa.services'. Adding certificate verification is strongly advised." Not sure what that means, or if it matters.

**Comment by kavezo** [comment]
Ooh, sorry, just saw this >.< I'll have to look into it -- it's possible that the server is assuming you already played a mirrors battle on it before you actually have

**Comment by kavezo** [comment]
ahah forgot to follow up -- this should be fixed in the latest release.
